apiVersion: v1
appVersion: "2.9.0"
name: artemis
description: A Helm chart installing Apache ActiveMQ Artemis
version: ${project.version}
icon: https://raw.githubusercontent.com/apache/activemq-artemis/2.9.0/artemis-website/src/main/resources/images/artemis-logo.png
maintainers:
  - name: Device Insight GmbH
